Settings:
  Sounds:
    # Sound to play when a player deposits items to a team chest
    TeamChest: "BLOCK_CHEST_CLOSE"
    # Sound to play when a player deposits items to a private chest
    PrivateChest: "BLOCK_CHEST_CLOSE"

  Double-Click:
    # Enables double-clicking to deposit items
    Enabled: false
    # Time in ticks in which the plugin will wait for the second click (20 ticks = 1 second)
    Wait-Time: 10

  Holograms:
    # Enable holograms
    Enabled: true
    Remove-After-Deposit:
      # Removes the hologram for the player after depositing items
      Enabled: true
      # Removes both the private and the team chest hologram
      Remove-Both: true
    # Hologram text
    Text:
      - "&7PUNCH TO"
      - "&7DEPOSIT"
    # Radius that the plugin will try to locate private/team chests
    Search:
      X: 8
      Y: 4
      Z: 8
    # Hologram offset
    Offsets:
      X: 0.5
      Y: 1.0
      Z: 0.5

  # Items that won't be deposited when left-clicking a container
  BlackListed-Items:
   - "WOOD_SWORD"
   - "STONE_SWORD"
   - "IRON_SWORD"
   - "DIAMOND_SWORD"
   - "BOW"
   - "WOOD_PICKAXE"
   - "WOOD_AXE"
   - "SHEARS"

Update-Check:
  # Checks for plugin updates
  Enabled: true

Debug-Mode:
  # Enables debug mode
  Enabled: false

# DO NOT TOUCH!
Config-Version: 4